app_name                      = "emblem-browser-use-prod"
environment                   = "prod"
env_file_key                  = "computer_use_env_prod"
sqs_queue_name                = "availability_requests_prod"
emblem_platform_sqs_queue_arn = "arn:aws:sqs:us-east-2:339713015370:emblem-platform-prod-prod-queue"
